//! Drives the delegation circuit (vendored, with the Vouch threshold modification) to prove
//! and verify `HoldsAtLeast` claims.
//!
//! The envelope is bound into the proof by the holder's spend-authorisation signature: the
//! key the circuit proves controls the notes (`rk`) signs the statement and every public input,
//! which a viewing-key holder cannot do. The circuit's `vote_round_id` (and from it the nullifier
//! domain and the five tags) is, in version 1, the statement hash — a second binding; in version
//! 2 it is the scope (circuit, audience, epoch), so the same note gives the same tag inside one
//! scope and reuse becomes visible to that verifier.
//!
//! Carried public inputs, in order (9 × 32 bytes):
//! `nf_signed, rk, cmx_new, van_comm, gov_null_1..5`. Everything else — `vote_round_id`,
//! `dom`, `nc_root`, `nf_imt_root`, `min_ballots` — the verifier derives itself.
//! Circuit 2 (exit certificates) carries six more: `reveal` and `revealed_nf_1..5`, the real
//! nullifiers of the proven notes (zero when `reveal` is 0).

use pof_core::{scope_id, signing_message, statement_hash, Claim, Envelope, CIRCUIT_REVEAL, CIRCUIT_THRESHOLD, FORMAT_V1};
use voting_circuits::delegation::{derive_nullifier_domain, Circuit, Instance, RevealCircuit, K};
use voting_circuits::ff::PrimeField;
use voting_crypto_deps::halo2_proofs::{
    pasta::EqAffine,
    plonk::{self, keygen_vk, keygen_vk_from_commitments, verify_proof, vk_commitments, SingleVerifier},
    poly::commitment::Params,
    transcript::{Blake2bRead, Challenge255},
};
use voting_crypto_deps::orchard::{
    note::nullifier::Nullifier,
    primitives::redpallas::{self, SpendAuth},
};
use voting_crypto_deps::pasta_curves::group::GroupEncoding;
use voting_crypto_deps::pasta_curves::pallas;

/// Serialized IPA parameters for K = 12 (`Params::write`), generated by
/// `cargo test -p pof-zk --release -- --ignored write_embedded_keys`.
const EMBEDDED_PARAMS: &[u8] = include_bytes!("../keys/params-k12.bin");
/// The delegation verifying key's commitments (see `encode_commitments`): circuit 1.
const EMBEDDED_VK: &[u8] = include_bytes!("../keys/vk-delegation.bin");
/// The exit-certificate circuit's verifying key commitments: circuit 2.
const EMBEDDED_VK_REVEAL: &[u8] = include_bytes!("../keys/vk-reveal.bin");

mod tree;
pub use tree::NoteTree;

#[cfg(feature = "prove")]
mod prove;
#[cfg(feature = "prove")]
pub use prove::{prove_holding, HeldNote, ProveError};

pub use voting_circuits::delegation::{DenseImtProvider, ImtProvider};

/// Number of public inputs a holding proof carries (circuit 1).
pub const CARRIED_INPUTS: usize = 9;
/// Number of public inputs an exit certificate carries (circuit 2): the reveal flag and five
/// revealed nullifiers on top.
pub const CARRIED_INPUTS_REVEAL: usize = 15;

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ZkError {
    #[error("the claim kind is not provable by a holding proof")]
    UnsupportedClaim,
    #[error("this verifier has no key for circuit {0}")]
    UnsupportedCircuit(u8),
    #[error("the threshold is not a whole number of 0.125 ZEC units")]
    NotWholeUnits,
    #[error("evidence carries {0} public inputs, not the number its circuit takes")]
    InputCount(usize),
    #[error("a public input is not a canonical field element")]
    NonCanonical,
    #[error("the same note is counted more than once")]
    DuplicateNote,
    #[error("the spend-authorisation key is not a valid point")]
    BadKey,
    #[error("the spend-authorisation signature does not verify")]
    BadSignature,
    #[error("the zero-knowledge proof does not verify")]
    ProofInvalid,
    #[error("key generation failed: {0}")]
    Keygen(String),
}

/// The circuit's `vote_round_id`: the statement hash (version 1) or the scope (version 2), as a
/// Pallas base element with the top two bits cleared, so always canonical.
pub fn round_id(env: &Envelope) -> pallas::Base {
    let mut b = if env.wire_version() == FORMAT_V1 { statement_hash(env) } else { scope_key(env) };
    b[31] &= 0x3f;
    pallas::Base::from_repr(b).expect("< 2^254 is canonical")
}

/// The key a verifier files this proof's tags under for reuse detection. In version 1 every
/// proof is its own scope (the round id is the statement), so tags never repeat across proofs.
pub fn scope_key(env: &Envelope) -> [u8; 32] {
    if env.wire_version() == FORMAT_V1 {
        statement_hash(env)
    } else {
        scope_id(env.circuit, &env.audience, env.epoch)
    }
}

/// The five per-note tags a proof carries (`gov_null_1..5`), for reuse detection inside a scope.
/// Padding slots carry random tags, so a verifier may record all five.
pub fn tags(env: &Envelope) -> Vec<[u8; 32]> {
    env.evidence.public_inputs.get(4..9).map(<[_]>::to_vec).unwrap_or_default()
}

pub fn base_from_bytes(b: &[u8; 32]) -> Result<pallas::Base, ZkError> {
    Option::from(pallas::Base::from_repr(*b)).ok_or(ZkError::NonCanonical)
}

pub fn base_to_bytes(x: &pallas::Base) -> [u8; 32] {
    x.to_repr()
}

/// Parameters and verifying keys for both circuits. Built once per process; no proving key, no
/// randomness.
pub struct Verifier {
    params: Params<EqAffine>,
    vk: plonk::VerifyingKey<EqAffine>,
    vk_reveal: plonk::VerifyingKey<EqAffine>,
}

impl std::fmt::Debug for Verifier {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Verifier { k: 12 }")
    }
}

impl Verifier {
    /// Loads the embedded parameters and verifying-key commitments: synthesis only, no MSMs.
    /// A native test (`embedded_vk_matches_keygen`) proves the embedded key equals `keygen_vk`.
    pub fn new() -> Result<Self, ZkError> {
        let params = Params::read(&mut &EMBEDDED_PARAMS[..]).map_err(|e| ZkError::Keygen(e.to_string()))?;
        let (fixed, perm) = decode_commitments(EMBEDDED_VK).ok_or_else(|| ZkError::Keygen("embedded key is corrupt".into()))?;
        let vk = keygen_vk_from_commitments(&params, &Circuit::default(), fixed, perm).map_err(|e| ZkError::Keygen(format!("{e:?}")))?;
        let (fixed, perm) = decode_commitments(EMBEDDED_VK_REVEAL).ok_or_else(|| ZkError::Keygen("embedded reveal key is corrupt".into()))?;
        let vk_reveal =
            keygen_vk_from_commitments(&params, &RevealCircuit::default(), fixed, perm).map_err(|e| ZkError::Keygen(format!("{e:?}")))?;
        Ok(Verifier { params, vk, vk_reveal })
    }

    /// Derive parameters and key from scratch (slow in WebAssembly; used to generate and
    /// check the embedded copies).
    pub fn derive() -> Result<Self, ZkError> {
        let params = Params::new(K);
        let vk = keygen_vk(&params, &Circuit::default()).map_err(|e| ZkError::Keygen(format!("{e:?}")))?;
        let vk_reveal = keygen_vk(&params, &RevealCircuit::default()).map_err(|e| ZkError::Keygen(format!("{e:?}")))?;
        Ok(Verifier { params, vk, vk_reveal })
    }

    /// The bytes to embed: `(params, circuit 1 commitments, circuit 2 commitments)`.
    pub fn export(&self) -> (Vec<u8>, Vec<u8>, Vec<u8>) {
        let mut params = vec![];
        self.params.write(&mut params).expect("writing to a Vec");
        let (fixed, perm) = vk_commitments(&self.vk);
        let (fixed_r, perm_r) = vk_commitments(&self.vk_reveal);
        (params, encode_commitments(&fixed, &perm), encode_commitments(&fixed_r, &perm_r))
    }

    fn vk_for(&self, circuit: u8) -> &plonk::VerifyingKey<EqAffine> {
        if circuit == CIRCUIT_REVEAL {
            &self.vk_reveal
        } else {
            &self.vk
        }
    }

    /// A short fingerprint of the verifying key (the first 8 bytes of its blake2b-256), for
    /// display and for pinning in receipts.
    pub fn fingerprint(&self) -> String {
        let (fixed, perm) = vk_commitments(&self.vk);
        let h = blake2b_simd::Params::new().hash_length(32).personal(b"vouch-vk-v1\0\0\0\0\0").hash(&encode_commitments(&fixed, &perm));
        h.as_bytes()[..8].iter().map(|b| format!("{b:02x}")).collect()
    }

    /// Verify the evidence of a `HoldsAtLeast` envelope. The caller has already checked
    /// that `env.anchor` matches an authenticated anchor; this checks signature and proof.
    pub fn verify_holding(&self, env: &Envelope) -> Result<(), ZkError> {
        let (instance, rk) = parts(env)?;

        // Signature first: it is cheap and binds the statement to the proof's rk.
        let sig = redpallas::Signature::<SpendAuth>::from(env.evidence.signature);
        rk.verify(&signing_message(env), &sig).map_err(|_| ZkError::BadSignature)?;

        let public_inputs = instance.to_halo2_instance();
        let mut reader = &env.evidence.proof[..];
        let mut transcript = Blake2bRead::<_, EqAffine, Challenge255<_>>::init(&mut reader);
        verify_proof(&self.params, self.vk_for(env.circuit), SingleVerifier::new(&self.params), &[&[&public_inputs]], &mut transcript)
            .map_err(|_| ZkError::ProofInvalid)?;
        if !reader.is_empty() {
            return Err(ZkError::ProofInvalid);
        }
        Ok(())
    }
}

impl Verifier {
    /// Verify many envelopes, one result each. Signatures are checked one by one (cheap); with the
    /// `batch` feature the Halo2 proofs are then checked together, with one multi-scalar
    /// multiplication for all their openings, and only when that fails is each re-checked alone
    /// to say which. Without the feature, each is checked alone.
    pub fn verify_many(&self, envs: &[Envelope]) -> Vec<Result<(), ZkError>> {
        #[cfg(feature = "batch")]
        {
            use voting_crypto_deps::halo2_proofs::plonk::BatchVerifier;
            let mut out: Vec<Result<(), ZkError>> = Vec::with_capacity(envs.len());
            let mut batch = BatchVerifier::new();
            let mut proof_len = None;
            for env in envs {
                let checked = parts(env).and_then(|(instance, rk)| {
                    let sig = redpallas::Signature::<SpendAuth>::from(env.evidence.signature);
                    rk.verify(&signing_message(env), &sig).map_err(|_| ZkError::BadSignature)?;
                    // The batch verifier does not see trailing proof bytes; a proof's length is fixed
                    // by the circuit, so every member must match the first one, checked alone below.
                    if *proof_len.get_or_insert(env.evidence.proof.len()) != env.evidence.proof.len() {
                        return Err(ZkError::ProofInvalid);
                    }
                    Ok(instance)
                });
                if let Ok(instance) = &checked {
                    batch.add_proof(vec![vec![instance.to_halo2_instance()]], env.evidence.proof.clone());
                }
                out.push(checked.map(|_| ()));
            }
            let first_ok = envs.iter().zip(&out).find(|(_, r)| r.is_ok()).map(|(e, _)| self.verify_holding(e).is_ok()).unwrap_or(true);
            // One key per batch: members of a batch share a scope, and so a circuit.
            let one_circuit = envs.windows(2).all(|w| w[0].circuit == w[1].circuit);
            let vk = self.vk_for(envs.first().map_or(CIRCUIT_THRESHOLD, |e| e.circuit));
            if first_ok && one_circuit && batch.finalize(&self.params, vk) {
                return out;
            }
            // Something in the batch is wrong: find out which, one by one.
            envs.iter().zip(out).map(|(e, r)| r.and_then(|()| self.verify_holding(e))).collect()
        }
        #[cfg(not(feature = "batch"))]
        envs.iter().map(|e| self.verify_holding(e)).collect()
    }
}

/// The circuit's `min_ballots` for a claim. Only whole-unit `HoldsAtLeast` claims are provable.
pub(crate) fn min_ballots(claim: &Claim) -> Result<u64, ZkError> {
    match claim {
        Claim::HoldsAtLeast { .. } => claim.min_units().ok_or(ZkError::NotWholeUnits),
        _ => Err(ZkError::UnsupportedClaim),
    }
}

/// Rebuild the circuit's 15 public inputs from an envelope: 9 carried, 6 derived.
pub fn instance_for(env: &Envelope) -> Result<Instance, ZkError> {
    parts(env).map(|(instance, _)| instance)
}

/// The instance, and the proof's `rk` parsed once for the signature check as well.
fn parts(env: &Envelope) -> Result<(Instance, redpallas::VerificationKey<SpendAuth>), ZkError> {
    let carried = match env.circuit {
        CIRCUIT_THRESHOLD => CARRIED_INPUTS,
        CIRCUIT_REVEAL => CARRIED_INPUTS_REVEAL,
        c => return Err(ZkError::UnsupportedCircuit(c)),
    };
    let min = min_ballots(&env.claim)?;
    let pi = &env.evidence.public_inputs;
    if pi.len() != carried {
        return Err(ZkError::InputCount(pi.len()));
    }
    let nf_signed = base_from_bytes(&pi[0])?;
    let rk = redpallas::VerificationKey::<SpendAuth>::try_from(pi[1]).map_err(|_| ZkError::BadKey)?;
    let cmx_new = base_from_bytes(&pi[2])?;
    let van_comm = base_from_bytes(&pi[3])?;
    let mut gov_null = [pallas::Base::from(0u64); 5];
    for (slot, bytes) in gov_null.iter_mut().zip(&pi[4..9]) {
        *slot = base_from_bytes(bytes)?;
    }
    // The circuit checks each of the 5 slots on its own; upstream relies on the vote chain to
    // refuse a repeated gov_null. Nothing downstream of Vouch does, so the verifier must: the
    // same note in two slots always yields the same gov_null = Poseidon(nk, dom, nf), and would
    // otherwise be summed twice. Honest padding notes have random nullifiers, so never collide.
    if pi[4..9].iter().enumerate().any(|(i, a)| pi[4 + i + 1..9].contains(a)) {
        return Err(ZkError::DuplicateNote);
    }
    let round = round_id(env);
    let nc_root = base_from_bytes(&env.anchor.nc_root)?;
    let nf_root = base_from_bytes(&env.anchor.nf_root)?;
    // nc_root is the tree at anchor.nc_height and nf_root the spent set at anchor.height; the
    // circuit takes them as independent inputs, and the verifier has already matched each to an
    // authenticated anchor at its own height.
    let instance = Instance::from_parts(
        Nullifier::from_inner(nf_signed),
        rk.clone(),
        cmx_new,
        van_comm,
        round,
        nc_root,
        nf_root,
        gov_null,
        derive_nullifier_domain(round),
    )
    .map_err(|_| ZkError::BadKey)?;
    let mut instance = instance.with_min_ballots(min);
    if env.circuit == CIRCUIT_REVEAL {
        // The flag must be a canonical 0 or 1; the circuit also constrains it.
        let flag = base_from_bytes(&pi[9])?;
        let reveal = if flag == pallas::Base::from(1u64) {
            true
        } else if flag == pallas::Base::from(0u64) {
            false
        } else {
            return Err(ZkError::ProofInvalid);
        };
        let mut nfs = [pallas::Base::from(0u64); 5];
        for (slot, bytes) in nfs.iter_mut().zip(&pi[10..15]) {
            *slot = base_from_bytes(bytes)?;
        }
        instance = instance.with_reveal(reveal, nfs);
    }
    Ok((instance, rk))
}

/// The real nullifiers an exit certificate publishes (circuit 2, reveal = 1), in slot order. A
/// deposit made with the certified notes reveals a subset of these on chain; padding slots'
/// nullifiers never appear. `None` for any other proof.
pub fn revealed_nullifiers(env: &Envelope) -> Option<[[u8; 32]; 5]> {
    let pi = &env.evidence.public_inputs;
    if env.circuit != CIRCUIT_REVEAL || pi.len() != CARRIED_INPUTS_REVEAL || pi[9] != base_to_bytes(&pallas::Base::from(1u64)) {
        return None;
    }
    pi[10..15].try_into().ok()
}

/// `u32 LE count ‖ 32-byte points` for fixed commitments, then the same for permutation.
fn encode_commitments(fixed: &[EqAffine], perm: &[EqAffine]) -> Vec<u8> {
    let mut out = Vec::with_capacity(8 + 32 * (fixed.len() + perm.len()));
    for set in [fixed, perm] {
        out.extend_from_slice(&(set.len() as u32).to_le_bytes());
        for p in set {
            out.extend_from_slice(p.to_bytes().as_ref());
        }
    }
    out
}

fn decode_commitments(mut b: &[u8]) -> Option<(Vec<EqAffine>, Vec<EqAffine>)> {
    let mut read_set = || -> Option<Vec<EqAffine>> {
        let n = u32::from_le_bytes(b.get(..4)?.try_into().ok()?) as usize;
        b = &b[4..];
        let mut v = Vec::with_capacity(n);
        for _ in 0..n {
            let mut repr = <EqAffine as GroupEncoding>::Repr::default();
            repr.as_mut().copy_from_slice(b.get(..32)?);
            b = &b[32..];
            v.push(Option::from(EqAffine::from_bytes(&repr))?);
        }
        Some(v)
    };
    let fixed = read_set()?;
    let perm = read_set()?;
    Some((fixed, perm))
}

#[cfg(test)]
mod keys {
    use super::*;

    fn dir() -> std::path::PathBuf {
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("keys")
    }

    /// Regenerate the embedded parameters and key after any circuit change.
    #[test]
    #[ignore = "writes keys/; run after changing the circuit"]
    fn write_embedded_keys() {
        let (params, vk, vk_reveal) = Verifier::derive().unwrap().export();
        std::fs::write(dir().join("params-k12.bin"), params).unwrap();
        std::fs::write(dir().join("vk-delegation.bin"), vk).unwrap();
        std::fs::write(dir().join("vk-reveal.bin"), vk_reveal).unwrap();
    }

    /// The embedded key is exactly the key `keygen_vk` derives for this circuit.
    #[test]
    fn embedded_vk_matches_keygen() {
        assert!(!EMBEDDED_VK.is_empty(), "run write_embedded_keys first");
        let derived = Verifier::derive().unwrap();
        let loaded = Verifier::new().unwrap();
        assert_eq!(derived.export(), loaded.export());
        assert_eq!(format!("{:?}", derived.vk.pinned()), format!("{:?}", loaded.vk.pinned()));
        assert_eq!(format!("{:?}", derived.vk_reveal.pinned()), format!("{:?}", loaded.vk_reveal.pinned()));
    }
}
