//! Drives the delegation circuit (vendored, with the Vouch threshold modification) to prove
//! and verify `HoldsAtLeast` claims.
//!
//! The envelope is bound into the proof: the circuit's `vote_round_id` is derived from the
//! statement hash (claim, audience, binding, anchor, issue, expiry, revocation), so changing
//! any of those fields invalidates the proof. The holder's spend-authorisation key signs the
//! statement and the public inputs under the proof's `rk`, which a viewing-key holder cannot do.
//!
//! Carried public inputs, in order (9 × 32 bytes):
//! `nf_signed, rk, cmx_new, van_comm, gov_null_1..5`. Everything else — `vote_round_id`,
//! `dom`, `nc_root`, `nf_imt_root`, `min_ballots` — the verifier derives itself.

use pof_core::{signing_message, statement_hash, Claim, Envelope};
use voting_circuits::delegation::{derive_nullifier_domain, Circuit, Instance, K};
use voting_circuits::ff::PrimeField;
use voting_crypto_deps::halo2_proofs::{
    pasta::EqAffine,
    plonk::{self, keygen_vk, keygen_vk_from_commitments, verify_proof, vk_commitments, SingleVerifier},
    poly::commitment::Params,
    transcript::{Blake2bRead, Challenge255},
};
use voting_crypto_deps::orchard::{
    note::nullifier::Nullifier,
    primitives::redpallas::{self, SpendAuth},
};
use voting_crypto_deps::pasta_curves::group::GroupEncoding;
use voting_crypto_deps::pasta_curves::pallas;

/// Serialized IPA parameters for K = 12 (`Params::write`), generated by
/// `cargo test -p pof-zk --release -- --ignored write_embedded_keys`.
const EMBEDDED_PARAMS: &[u8] = include_bytes!("../keys/params-k12.bin");
/// The delegation verifying key's commitments (see `encode_commitments`).
const EMBEDDED_VK: &[u8] = include_bytes!("../keys/vk-delegation.bin");

mod tree;
pub use tree::NoteTree;

#[cfg(feature = "prove")]
mod prove;
#[cfg(feature = "prove")]
pub use prove::{prove_holding, HeldNote, ProveError};

pub use voting_circuits::delegation::{DenseImtProvider, ImtProvider};

/// Number of public inputs a holding proof carries.
pub const CARRIED_INPUTS: usize = 9;

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ZkError {
    #[error("the claim kind is not provable by a holding proof")]
    UnsupportedClaim,
    #[error("the threshold is not a whole number of 0.125 ZEC units")]
    NotWholeUnits,
    #[error("evidence carries {0} public inputs, expected 9")]
    InputCount(usize),
    #[error("a public input is not a canonical field element")]
    NonCanonical,
    #[error("the spend-authorisation key is not a valid point")]
    BadKey,
    #[error("the spend-authorisation signature does not verify")]
    BadSignature,
    #[error("the zero-knowledge proof does not verify")]
    ProofInvalid,
    #[error("key generation failed: {0}")]
    Keygen(String),
}

/// The statement hash as a Pallas base element: top two bits cleared, so always canonical.
pub fn round_id(env: &Envelope) -> pallas::Base {
    let mut b = statement_hash(env);
    b[31] &= 0x3f;
    pallas::Base::from_repr(b).expect("< 2^254 is canonical")
}

pub fn base_from_bytes(b: &[u8; 32]) -> Result<pallas::Base, ZkError> {
    Option::from(pallas::Base::from_repr(*b)).ok_or(ZkError::NonCanonical)
}

pub fn base_to_bytes(x: &pallas::Base) -> [u8; 32] {
    x.to_repr()
}

/// Parameters and verifying key for the delegation circuit. Built once per process;
/// no proving key, no randomness.
pub struct Verifier {
    params: Params<EqAffine>,
    vk: plonk::VerifyingKey<EqAffine>,
}

impl std::fmt::Debug for Verifier {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Verifier { k: 12 }")
    }
}

impl Verifier {
    /// Loads the embedded parameters and verifying-key commitments: synthesis only, no MSMs.
    /// A native test (`embedded_vk_matches_keygen`) proves the embedded key equals `keygen_vk`.
    pub fn new() -> Result<Self, ZkError> {
        if EMBEDDED_PARAMS.is_empty() || EMBEDDED_VK.is_empty() {
            return Self::derive();
        }
        let params = Params::read(&mut &EMBEDDED_PARAMS[..]).map_err(|e| ZkError::Keygen(e.to_string()))?;
        let (fixed, perm) = decode_commitments(EMBEDDED_VK).ok_or_else(|| ZkError::Keygen("embedded key is corrupt".into()))?;
        let vk = keygen_vk_from_commitments(&params, &Circuit::default(), fixed, perm).map_err(|e| ZkError::Keygen(format!("{e:?}")))?;
        Ok(Verifier { params, vk })
    }

    /// Derive parameters and key from scratch (slow in WebAssembly; used to generate and
    /// check the embedded copies).
    pub fn derive() -> Result<Self, ZkError> {
        let params = Params::new(K);
        let vk = keygen_vk(&params, &Circuit::default()).map_err(|e| ZkError::Keygen(format!("{e:?}")))?;
        Ok(Verifier { params, vk })
    }

    /// The bytes to embed: `(params, commitments)`.
    pub fn export(&self) -> (Vec<u8>, Vec<u8>) {
        let mut params = vec![];
        self.params.write(&mut params).expect("writing to a Vec");
        let (fixed, perm) = vk_commitments(&self.vk);
        (params, encode_commitments(&fixed, &perm))
    }

    /// A short fingerprint of the verifying key, for display and for pinning in receipts.
    pub fn fingerprint(&self) -> String {
        let (fixed, perm) = vk_commitments(&self.vk);
        let enc = encode_commitments(&fixed, &perm);
        let mut h = [0u8; 8];
        for (i, b) in enc.iter().enumerate() {
            h[i % 8] ^= b.rotate_left((i / 8 % 8) as u32);
        }
        h.iter().map(|b| format!("{b:02x}")).collect()
    }

    /// Verify the evidence of a `HoldsAtLeast` envelope. The caller has already checked
    /// that `env.anchor` matches an authenticated anchor; this checks signature and proof.
    pub fn verify_holding(&self, env: &Envelope) -> Result<(), ZkError> {
        let instance = instance_for(env)?;

        // Signature first: it is cheap and binds the statement to the proof's rk.
        let rk_bytes = env.evidence.public_inputs[1];
        let rk = redpallas::VerificationKey::<SpendAuth>::try_from(rk_bytes).map_err(|_| ZkError::BadKey)?;
        let sig = redpallas::Signature::<SpendAuth>::from(env.evidence.signature);
        rk.verify(&signing_message(env), &sig).map_err(|_| ZkError::BadSignature)?;

        let public_inputs = instance.to_halo2_instance();
        let mut reader = &env.evidence.proof[..];
        let mut transcript = Blake2bRead::<_, EqAffine, Challenge255<_>>::init(&mut reader);
        verify_proof(&self.params, &self.vk, SingleVerifier::new(&self.params), &[&[&public_inputs]], &mut transcript)
            .map_err(|_| ZkError::ProofInvalid)?;
        if !reader.is_empty() {
            return Err(ZkError::ProofInvalid);
        }
        Ok(())
    }
}

/// Rebuild the circuit's 15 public inputs from an envelope: 9 carried, 6 derived.
pub fn instance_for(env: &Envelope) -> Result<Instance, ZkError> {
    let min = match env.claim {
        Claim::HoldsAtLeast { .. } => env.claim.min_units().ok_or(ZkError::NotWholeUnits)?,
        _ => return Err(ZkError::UnsupportedClaim),
    };
    let pi = &env.evidence.public_inputs;
    if pi.len() != CARRIED_INPUTS {
        return Err(ZkError::InputCount(pi.len()));
    }
    let nf_signed = base_from_bytes(&pi[0])?;
    let rk = redpallas::VerificationKey::<SpendAuth>::try_from(pi[1]).map_err(|_| ZkError::BadKey)?;
    let cmx_new = base_from_bytes(&pi[2])?;
    let van_comm = base_from_bytes(&pi[3])?;
    let mut gov_null = [pallas::Base::from(0u64); 5];
    for (slot, bytes) in gov_null.iter_mut().zip(&pi[4..9]) {
        *slot = base_from_bytes(bytes)?;
    }
    let round = round_id(env);
    let nc_root = base_from_bytes(&env.anchor.nc_root)?;
    let nf_root = base_from_bytes(&env.anchor.nf_root)?;
    Instance::from_parts(
        Nullifier::from_inner(nf_signed),
        rk,
        cmx_new,
        van_comm,
        round,
        nc_root,
        nf_root,
        gov_null,
        derive_nullifier_domain(round),
    )
    .map(|i| i.with_min_ballots(min))
    .map_err(|_| ZkError::BadKey)
}

/// `u32 LE count ‖ 32-byte points` for fixed commitments, then the same for permutation.
fn encode_commitments(fixed: &[EqAffine], perm: &[EqAffine]) -> Vec<u8> {
    let mut out = Vec::with_capacity(8 + 32 * (fixed.len() + perm.len()));
    for set in [fixed, perm] {
        out.extend_from_slice(&(set.len() as u32).to_le_bytes());
        for p in set {
            out.extend_from_slice(p.to_bytes().as_ref());
        }
    }
    out
}

fn decode_commitments(mut b: &[u8]) -> Option<(Vec<EqAffine>, Vec<EqAffine>)> {
    let mut read_set = || -> Option<Vec<EqAffine>> {
        let n = u32::from_le_bytes(b.get(..4)?.try_into().ok()?) as usize;
        b = &b[4..];
        let mut v = Vec::with_capacity(n);
        for _ in 0..n {
            let mut repr = <EqAffine as GroupEncoding>::Repr::default();
            repr.as_mut().copy_from_slice(b.get(..32)?);
            b = &b[32..];
            v.push(Option::from(EqAffine::from_bytes(&repr))?);
        }
        Some(v)
    };
    let fixed = read_set()?;
    let perm = read_set()?;
    Some((fixed, perm))
}

#[cfg(test)]
mod keys {
    use super::*;

    fn dir() -> std::path::PathBuf {
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("keys")
    }

    /// Regenerate the embedded parameters and key after any circuit change.
    #[test]
    #[ignore = "writes keys/; run after changing the circuit"]
    fn write_embedded_keys() {
        let (params, vk) = Verifier::derive().unwrap().export();
        std::fs::write(dir().join("params-k12.bin"), params).unwrap();
        std::fs::write(dir().join("vk-delegation.bin"), vk).unwrap();
    }

    /// The embedded key is exactly the key `keygen_vk` derives for this circuit.
    #[test]
    fn embedded_vk_matches_keygen() {
        assert!(!EMBEDDED_VK.is_empty(), "run write_embedded_keys first");
        let derived = Verifier::derive().unwrap();
        let loaded = Verifier::new().unwrap();
        assert_eq!(derived.export(), loaded.export());
        assert_eq!(format!("{:?}", derived.vk.pinned()), format!("{:?}", loaded.vk.pinned()));
    }
}
